---
- name: Test connection to F5 host
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    provider:
      user: "admin"
      password: "test123"
      server: "test.com"
      validate_certs: false
  tasks:
    - name: Execute show command to test authentication
      f5networks.f5_modules.bigip_command:
        provider: "{{ provider }}"
        commands:
          - "tmsh show running-config ltm profile"
    - name: run show version on remote devices
      bigip_command:
       commands: show sys version
       provider:
        server: lb.mydomain.com
        password: secret
        user: admin
      delegate_to: localhost
